# Generated by Django 4.2.20 on 2025-03-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stock_security_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='security_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
