# Generated by Django 4.2.20 on 2025-07-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_prediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('security_id', models.CharField(max_length=20, null=True)),
                ('industry', models.CharField(max_length=255, null=True)),
                ('sector_index', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'api_stock',
                'managed': False,
            },
        ),
    ]
