import React from 'react';
import { Box, Card, CardContent, Typography, Grid, Tooltip } from '@mui/material';

const FinancialOverviewSection = ({ allFinancialMetrics, colors }) => {
  const metricExplanations = {
    "Prev Close": "The closing price of the stock on the previous trading day.",
    "Open": "The price at which the stock started trading at the beginning of the trading day.",
    "24H Volume": "The total number of shares traded for the stock within the last 24 hours.",
    "Market Cap": "Market Capitalization: The total value of a company's outstanding shares, calculated by multiplying the current share price by the number of shares outstanding.",
    "P/E Ratio": "Price-to-Earnings Ratio: A valuation ratio that compares a company's current share price to its earnings per share (EPS).",
    "Dividend Yield": "The dividend per share divided by the share price, expressed as a percentage. It indicates the return on investment from dividends.",
    "Day Range": "The highest and lowest prices at which a stock has traded during the current trading day.",
    "52W Range": "The highest and lowest prices at which a stock has traded over the past 52 weeks (one year).",
    "EPS": "Earnings Per Share: The portion of a company's profit allocated to each outstanding share of common stock.",
    "Beta": "A measure of a stock's volatility in relation to the overall market. A beta of 1 means the stock's price moves with the market.",
    "Book Value": "The total assets of a company minus its total liabilities, representing the net asset value of the company.",
    "Price to Book": "Price-to-Book Ratio: Compares a company's current market price to its book value per share.",
    "Operating Cash Flow": "The cash generated by a company's normal business operations.",
    "Free Cash Flow": "The cash a company generates after accounting for cash outflows to support operations and maintain its capital assets.",
    "Total Cash": "The total amount of cash and cash equivalents a company holds.",
    "Borrowing (Total Debt)": "The total amount of financial obligations owed by a company to its creditors.",
    "Total Revenue": "The total amount of income generated by the sale of goods or services related to the company's primary operations.",
    "Gross Profits": "The profit a company makes after deducting the costs associated with making and selling its products, or providing its services.",
    "EBITDA": "Earnings Before Interest, Taxes, Depreciation, and Amortization: A measure of a company's overall financial performance.",
    "Net Income": "The total profit of a company after all expenses, including taxes and interest, have been deducted from revenue.",
    "Shares Outstanding": "The total number of a company's shares of stock that are currently held by all its shareholders.",
    "Book Value per Share": "The book value of a company divided by the number of shares outstanding.",
    "Debt to Equity": "A financial ratio indicating the relative proportion of shareholders' equity and debt used to finance a company's assets.",
    "Current Ratio": "A liquidity ratio that measures a company's ability to pay off its short-term liabilities with its current assets.",
    "Quick Ratio": "A more stringent liquidity ratio that measures a company's ability to meet its short-term obligations with its most liquid assets.",
    "Return on Assets (%)": "A financial ratio that indicates how profitable a company is in relation to its total assets.",
    "Return on Equity (%)": "A financial ratio that measures the rate of return on the ownership interest (shareholders' equity) of the common stock owners.",
    "Profit Margins (%)": "The percentage of revenue that a company retains as profit. It indicates how many cents of profit are generated for each dollar of revenue.",
    "Operating Margins (%)": "A profitability ratio that measures how much profit a company makes from its operations, after paying for variable costs of production.",
    "EBITDA Margins (%)": "EBITDA divided by revenue, indicating a company's operating profitability as a percentage of its revenue."
  };

  const getMetricExplanation = (label) => metricExplanations[label] || `No detailed explanation available for ${label}.`;

  return (
    <>
      <Typography variant="h6" fontWeight="bold" color="white" sx={{px: 2, mb: 1.5}}>
        Financial Overview
      </Typography>
      <Card sx={{ 
        mb: 3,
        overflow: "hidden",
        bgcolor: colors.cardBg, 
        borderRadius: 3,
        boxShadow: 0, 
        border: `1px solid ${colors.divider}` 
      }}>
        <CardContent sx={{ p: 3, borderRadius: 3 }}>
          <Grid container spacing={0} columns={{ xs: 1, sm: 2, md: 4, lg: 4 }}> 
            {allFinancialMetrics.map((metric, index) => (
              <Grid item xs={1} sm={1} md={1} lg={1} key={index}> 
                <Tooltip title={getMetricExplanation(metric.label)} arrow placement="top">
                  <Box sx={{ 
                    display: 'flex', 
                    justifyContent: 'space-between', 
                    alignItems: 'center',
                    bgcolor: colors.cardBg,
                    py: 1.5, 
                    px: 1, 
                    borderBottom: `1px solid ${colors.divider}`, 
                    color: colors.textPrimary,
                    height: '100%', 
                    cursor: 'help',
                    '&:hover': { 
                      bgcolor: colors.background,
                    }
                  }}>
                    <Typography variant="body2" sx={{ color: colors.textSecondary, flexShrink: 0 }}>{metric.label}</Typography>
                    <Typography variant="body1" fontWeight="medium" sx={{ textAlign: 'right', flexGrow: 1, ml: 1 }}>{metric.value}</Typography>
                  </Box>
                </Tooltip>
              </Grid>
            ))}
          </Grid>
        </CardContent>
      </Card>
    </>
  );
};

export default FinancialOverviewSection;
